name: Python application test with Github Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.10, 3.11]
        orjson: ["", "orjson"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ "${{ matrix.orjson }}" != "" ]; then
          pip install ${{ matrix.orjson }}
        fi
        pip install -r requirements.txt
        pip install coverage
    - name: Run tests
      run: |
        coverage run -m unittest discover -s tests
    - name: Coverage report
      run: coverage report -m
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
    - name: Run tests with coverage
      run: |
        pip install coverage
        coverage run --source=my_package -m unittest discover -s tests
        coverage xml
